### ISSUE TITLE
lokey example doesn't work well

### ISSUE THREAD

**Issue by jpeach** [cloudflare/cloudflare-docs#3808]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/users/validating-json/#manual-verification

### Section that requires update

Telling people to use `lokey` seems really fraught. On macOS, I had to do:

```
$ brew install python
$ pip3.9 install lokey
$ pip3.9 install six==1.10.0
```
And it still doesn't work:

```
$ curl -s https://$DOMAIN/cdn-cgi/access/certs | jq '.keys[0]' | lokey to pem -----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA01SvMv4TgFIECQgzHaRL DGVaKhRQHjgdiSOpbqhHQMdcNtBIM0HAQbrs7YS6sQCCdZC5wCvlq3xgqdU5J6k YI5OCSsIWXKkobAl6PbXHdN0bJximeiHGa3O0hMREP6RKBoI6ayNmZ3WlVGWY 6ie47KGqN69l7fPKyZvszb4GdpxE0r8gllZZwIuPjzlghXRlrkaP48ucQwo+tq PSSdDdW57TCFmy+G547W5iWZWJIeNkfVu9t6FktvCwSZ1ekum3X7IQcd0O0DWSR Aj9tzNDPkzOeSFxmQkKpWs8Qw7ZBIfLOsO3DCH6VPNhS2cqhw1AAMunh8alDKQU aQIDAQAB -----END PUBLIC KEY-----
Traceback (most recent call last):
  File "/opt/homebrew/bin/lokey", line 5, in <module>
    from lokey import cli
  File "/opt/homebrew/lib/python3.9/site-packages/lokey/__init__.py", line 49
    print ctx.obj.key
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(ctx.obj.key)?
```
### What needs to change?

Use some tool that can reliably be installed and work.

**Comment by jpeach** [comment]
https://github.com/jpf/lokey/pull/7
https://github.com/jpf/lokey/pull/6
